// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojytxmiuitrjtrocfgei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qeXR4bWl1aXRyanRyb2NmZ2VpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjQ5OTEsImV4cCI6MjA3MjQwMDk5MX0.1FFcxQrU2W8m7ftS6VrmwXorvij7D8dmXq8OkTluXFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});