// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqpiwtaxwdhicicrtsgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxcGl3dGF4d2RoaWNpY3J0c2dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzOTc3OTksImV4cCI6MjA3MTk3Mzc5OX0.2Rtuq7hUUd9iHBCDM22wF8dtDEs4-Q5eHGUNmC4o8xQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});